# EDA BIZKAIBUS

## 1. Data Collection

In [1]:
import pandas as pd
import numpy as np

In [2]:
marzo_2024= pd.read_csv("bizkaibus/2024_biz_mar.csv")
junio_2024= pd.read_csv("bizkaibus/2024_biz_jun.csv")
sept_2024= pd.read_csv("bizkaibus/2024_biz_sept.csv")
dic_2024= pd.read_csv("bizkaibus/2024_biz_dic.csv")
marzo_2025= pd.read_csv("bizkaibus/2025_biz_mar.csv")
junio_2025= pd.read_csv("bizkaibus/2025_biz_jun.csv")
sept_2025= pd.read_csv("bizkaibus/2025_biz_sept.csv")
dic_2025= pd.read_csv("bizkaibus/2025_biz_dic.csv")

In [11]:
bizkaibus = pd.concat([marzo_2024, junio_2024, sept_2024, dic_2024, marzo_2025, junio_2025, sept_2025, dic_2025], ignore_index=True)
bizkaibus.info()

<class 'pandas.DataFrame'>
RangeIndex: 2280 entries, 0 to 2279
Data columns (total 44 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   _id                                                             2280 non-null   int64
 1   EKITALDIA/EJERCICIO                                             2280 non-null   int64
 2   HILABETE/MES                                                    2280 non-null   int64
 3   ZENBAKIA/CODIGO                                                 2280 non-null   str
 4   LERROA/LINEA                                                    2280 non-null   str
 5   CREDITRANS/CREDITRANS                                           2273 non-null   float64
 6   CREDITRANS F20/CREDITRANS F20                                   2259 non-null   float64
 7   CREDITRANS F50/CREDITRANS F50                                   2243 non-null   float64
 8   GIZATRANS/GIZATRANS                                             2271 non-null   float64
 9   GIZATRANS 20/GIZATRANS 20                                       2226 non-null   float64
 10  GIZATRANS 50/GIZATRANS 50                                       2173 non-null   float64
 11  BBCARD 24/BBCARD 24                                             2113 non-null   float64
 12  BBCARD 48/BBCARD 48                                             2105 non-null   float64
 13  BBCARD 72/BBCARD 72                                             2119 non-null   float64
 14  GAZTE 70/GAZTE 70                                               2251 non-null   float64
 15  GAZTE 70 F20/GAZTE 70 F20                                       2246 non-null   float64
 16  GAZTE 70 F50/GAZTE 70 F50                                       2218 non-null   float64
 17  GORO/GORO                                                       2252 non-null   float64
 18  GORO F20/GORO F20                                               2243 non-null   float64
 19  GORO F50/GORO F50                                               2209 non-null   float64
 20  B 50/B 50                                                       2250 non-null   float64
 21  B50 F20/B50 F20                                                 2222 non-null   float64
 22  B50 F50/B50 F50                                                 2133 non-null   float64
 23  B70/B70                                                         2246 non-null   float64
 24  B70 F20/B70 F20                                                 2182 non-null   float64
 25  B70 F50/B70 F50                                                 2120 non-null   float64
 26  BORO/BORO                                                       2250 non-null   float64
 27  BORO F20/BORO F20                                               2207 non-null   float64
 28  BORO F50/BORO F50                                               2187 non-null   float64
 29  OHIKOA/OCASIONAL                                                2280 non-null   float64
 30  FAMILIA UGARIA/FAMILIA NUMEROSA                                 2223 non-null   float64
 31  6 URTETIK BEHERAKOAK/MENORES DE 6 ANOS                          2275 non-null   float64
 32  ITSU-MUP-EN GIDARI-LAGUN/ACOMPANANTE INVIDENTE-PMRS             2252 non-null   float64
 33  METROA/METRO                                                    2208 non-null   float64
 34  T.M MATXURA/PUP AVERIADO                                        2208 non-null   float64
 35  ENPRESA/EMPRESA                                                 2280 non-null   int64
 36  GUZTIRA/TOTAL                                                   2280 non-null   float64
 37  BAT/BAT                                                         1710 non-null   float64
 38  BAT F20/BAT F20                                                 1710 non-null   float64
 39  BAT F50/BAT F50                                                 1710 non-null   float64
 40  BAT BEREZI/BAT BEREZI                                           1710 non-null   float64
 41  BAT BEREZI F20/BAT BEREZI F20                                   1710 non-null   float64
 42  BAT BEREZI F50/BAT BEREZI F50                                   1710 non-null   float64
 43  ITSU-MUPEN DOAKO GIDARILAGUN/ACOMPANANTE GRATIS INVIDENTE-PMRS  1710 non-null   float64
dtypes: float64(38), int64(4), str(2)
memory usage: 783.9 KB

Vamos a ir viendo si el dataset se ha creado correctamente, por ejemplo si los años y meses estan bien

In [9]:
bizkaibus['EKITALDIA/EJERCICIO'].unique()

array([2024, 2025])

In [10]:
bizkaibus['HILABETE/MES'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Tenemos dos columnas que acumulan muchos 0, METRO y PUP AVERIADO, si hago el sum miro a ver si en todas las filas es 0

In [12]:
bizkaibus['METROA/METRO'].sum()

np.float64(301.0)

In [ ]:
bizkaibus['T.M MATXURA/PUP AVERIADO'].sum()

''' 
Los dos resultados son bastante bajos, no parece que vaya a influir mucho en el análisis
De momento mantendré ambas columnas, sino más adelante las borro.
'''

np.float64(22.0)

Vamos a ver cuantos valores nulos hay

In [14]:
bizkaibus.isnull().sum()

_id                                                                 0
EKITALDIA/EJERCICIO                                                 0
HILABETE/MES                                                        0
ZENBAKIA/CODIGO                                                     0
LERROA/LINEA                                                        0
CREDITRANS/CREDITRANS                                               7
CREDITRANS F20/CREDITRANS F20                                      21
CREDITRANS F50/CREDITRANS F50                                      37
GIZATRANS/GIZATRANS                                                 9
GIZATRANS 20/GIZATRANS 20                                          54
GIZATRANS 50/GIZATRANS 50                                         107
BBCARD 24/BBCARD 24                                               167
BBCARD 48/BBCARD 48                                               175
BBCARD 72/BBCARD 72                                               161
GAZTE 70/GAZTE 70                                                  29
GAZTE 70 F20/GAZTE 70 F20                                          34
GAZTE 70 F50/GAZTE 70 F50                                          62
GORO/GORO                                                          28
GORO F20/GORO F20                                                  37
GORO F50/GORO F50                                                  71
B 50/B 50                                                          30
B50 F20/B50 F20                                                    58
B50 F50/B50 F50                                                   147
B70/B70                                                            34
B70 F20/B70 F20                                                    98
B70 F50/B70 F50                                                   160
BORO/BORO                                                          30
BORO F20/BORO F20                                                  73
BORO F50/BORO F50                                                  93
OHIKOA/OCASIONAL                                                    0
FAMILIA UGARIA/FAMILIA NUMEROSA                                    57
6 URTETIK BEHERAKOAK/MENORES DE 6 ANOS                              5
ITSU-MUP-EN GIDARI-LAGUN/ACOMPANANTE INVIDENTE-PMRS                28
METROA/METRO                                                       72
T.M MATXURA/PUP AVERIADO                                           72
ENPRESA/EMPRESA                                                     0
GUZTIRA/TOTAL                                                       0
BAT/BAT                                                           570
BAT F20/BAT F20                                                   570
BAT F50/BAT F50                                                   570
BAT BEREZI/BAT BEREZI                                             570
BAT BEREZI F20/BAT BEREZI F20                                     570
BAT BEREZI F50/BAT BEREZI F50                                     570
ITSU-MUPEN DOAKO GIDARILAGUN/ACOMPANANTE GRATIS INVIDENTE-PMRS    570
dtype: int64

Hay bastantes valores nulos y muchos se corresponden a títulos y bonos de Barik, que no existian en 2024. 
No merece borrar esas columnas por tanto hacemos 0 esos NAN.

In [19]:
bizkaibus.fillna(0, inplace=True)

,_id,EKITALDIA/EJERCICIO,HILABETE/MES,ZENBAKIA/CODIGO,LERROA/LINEA,CREDITRANS/CREDITRANS,CREDITRANS F20/CREDITRANS F20,CREDITRANS F50/CREDITRANS F50,GIZATRANS/GIZATRANS,GIZATRANS 20/GIZATRANS 20,...,T.M MATXURA/PUP AVERIADO,ENPRESA/EMPRESA,GUZTIRA/TOTAL,BAT/BAT,BAT F20/BAT F20,BAT F50/BAT F50,BAT BEREZI/BAT BEREZI,BAT BEREZI F20/BAT BEREZI F20,BAT BEREZI F50/BAT BEREZI F50,ITSU-MUPEN DOAKO GIDARILAGUN/ACOMPANANTE GRATIS INVIDENTE-PMRS
0,1,2024,1,A2610,GALDAKAO - UPV/EHU,5680.0,248.0,21.0,293.0,1.0,...,0.0,79,9.392,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,2024,1,A2611,UGAO MIRABALLES - BASAURI - ETXEBARRI - UPV/EHU,2745.0,74.0,12.0,317.0,0.0,...,0.0,62,4.732,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,2024,1,A3613,BILBAO - UGAO MIRABALLES - OROZKO,17502.0,257.0,18.0,8300.0,15.0,...,0.0,581,30.896,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,2024,1,A3622,BILBAO - BASAURI - Artunduaga - San Miguel -ZA...,6469.0,90.0,25.0,2326.0,6.0,...,0.0,161,10.917,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,2024,1,A3631,BILBAO - GALDAKAO - LARRABETZU,22794.0,524.0,115.0,6662.0,7.0,...,0.0,567,37.075,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,279,2025,12,A3524,BERMEO - BAKIO,0.0,0.0,0.0,0.0,0.0,...,0.0,0,859.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2276,280,2025,12,A3527,BILBAO - MUNGIA - BERMEO (Por la autopista/tik),60562.0,1989.0,175.0,10126.0,56.0,...,0.0,731,95310.000,19.0,5.0,0.0,2.0,0.0,0.0,0.0
2277,281,2025,12,A3528,BERMEO - MUNGIA - DERIO - UPV/EHU,3140.0,158.0,31.0,265.0,17.0,...,0.0,44,5903.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2278,284,2025,12,A3531,LEIOA-Hospital Urduliz Ospitalea - GATIKA -MUNGIA,10586.0,366.0,35.0,3283.0,5.0,...,0.0,154,19218.000,4.0,0.0,0.0,0.0,0.0,0.0,0.0
2279,285,2025,12,A3537,PLENTZIA-GORLIZ-MUNGIA,4059.0,105.0,39.0,1002.0,1.0,...,0.0,36,6555.000,3.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
bizkaibus.isnull().sum().sum()

np.int64(0)

Para que el trabajo sea mas sencillo vamos a eliminar el nombre en euskera de las columnas. Tenemos suerte que estan divididas por /
entonces si hacemos un split(/) y nos quedamos con la ultima parte [-1] se quedara solo el nombre en castellano

In [22]:
bizkaibus.columns

Index(['_id', 'EKITALDIA/EJERCICIO', 'HILABETE/MES', 'ZENBAKIA/CODIGO',
       'LERROA/LINEA', 'CREDITRANS/CREDITRANS',
       'CREDITRANS F20/CREDITRANS F20', 'CREDITRANS F50/CREDITRANS F50',
       'GIZATRANS/GIZATRANS', 'GIZATRANS 20/GIZATRANS 20',
       'GIZATRANS 50/GIZATRANS 50', 'BBCARD 24/BBCARD 24',
       'BBCARD 48/BBCARD 48', 'BBCARD 72/BBCARD 72', 'GAZTE 70/GAZTE 70',
       'GAZTE 70 F20/GAZTE 70 F20', 'GAZTE 70 F50/GAZTE 70 F50', 'GORO/GORO',
       'GORO F20/GORO F20', 'GORO F50/GORO F50', 'B 50/B 50',
       'B50 F20/B50 F20', 'B50 F50/B50 F50', 'B70/B70', 'B70 F20/B70 F20',
       'B70 F50/B70 F50', 'BORO/BORO', 'BORO F20/BORO F20',
       'BORO F50/BORO F50', 'OHIKOA/OCASIONAL',
       'FAMILIA UGARIA/FAMILIA NUMEROSA',
       '6 URTETIK BEHERAKOAK/MENORES DE 6 ANOS',
       'ITSU-MUP-EN GIDARI-LAGUN/ACOMPANANTE INVIDENTE-PMRS', 'METROA/METRO',
       'T.M MATXURA/PUP AVERIADO', 'ENPRESA/EMPRESA', 'GUZTIRA/TOTAL',
       'BAT/BAT', 'BAT F20/BAT F20', 'BAT F50/BAT F50',
       'BAT BEREZI/BAT BEREZI', 'BAT BEREZI F20/BAT BEREZI F20',
       'BAT BEREZI F50/BAT BEREZI F50',
       'ITSU-MUPEN DOAKO GIDARILAGUN/ACOMPANANTE GRATIS INVIDENTE-PMRS'],
      dtype='str')

In [23]:
'EKITALDIA/EJERCICIO'.split('/')

['EKITALDIA', 'EJERCICIO']

In [25]:
bizkaibus.columns = [col.split('/')[-1] for col in bizkaibus.columns]

In [26]:
bizkaibus.columns

Index(['_id', 'EJERCICIO', 'MES', 'CODIGO', 'LINEA', 'CREDITRANS',
       'CREDITRANS F20', 'CREDITRANS F50', 'GIZATRANS', 'GIZATRANS 20',
       'GIZATRANS 50', 'BBCARD 24', 'BBCARD 48', 'BBCARD 72', 'GAZTE 70',
       'GAZTE 70 F20', 'GAZTE 70 F50', 'GORO', 'GORO F20', 'GORO F50', 'B 50',
       'B50 F20', 'B50 F50', 'B70', 'B70 F20', 'B70 F50', 'BORO', 'BORO F20',
       'BORO F50', 'OCASIONAL', 'FAMILIA NUMEROSA', 'MENORES DE 6 ANOS',
       'ACOMPANANTE INVIDENTE-PMRS', 'METRO', 'PUP AVERIADO', 'EMPRESA',
       'TOTAL', 'BAT', 'BAT F20', 'BAT F50', 'BAT BEREZI', 'BAT BEREZI F20',
       'BAT BEREZI F50', 'ACOMPANANTE GRATIS INVIDENTE-PMRS'],
      dtype='str')

In [28]:
bizkaibus.describe()

,_id,EJERCICIO,MES,CREDITRANS,CREDITRANS F20,CREDITRANS F50,GIZATRANS,GIZATRANS 20,GIZATRANS 50,BBCARD 24,...,PUP AVERIADO,EMPRESA,TOTAL,BAT,BAT F20,BAT F50,BAT BEREZI,BAT BEREZI F20,BAT BEREZI F50,ACOMPANANTE GRATIS INVIDENTE-PMRS
count,2280.000000,2280.00000,2280.00000,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,...,2280.000000,2280.000000,2.280000e+03,2280.000000,2280.000000,2280.000000,2280.000000,2280.000000,2280.0,2280.000000
mean,143.000000,2024.50000,6.50000,18219.559213,532.015657,85.673246,4419.791115,20.907018,3.216667,0.298246,...,0.009649,368.167105,3.036337e+04,24.204386,1.384649,0.148246,0.690351,0.000877,0.0,0.187719
std,82.289955,0.50011,3.45281,27058.038611,868.325421,143.855355,5861.700312,36.132637,10.396040,2.486223,...,0.106374,620.542671,4.682794e+04,164.839338,6.704038,1.289219,4.915762,0.029611,0.0,2.852961
min,1.000000,2024.00000,1.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,72.000000,2024.00000,3.75000,3173.500000,89.000000,4.000000,321.750000,0.000000,0.000000,0.000000,...,0.000000,31.000000,5.310500e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
50%,143.000000,2024.50000,6.50000,11573.000000,351.500000,40.000000,2186.000000,8.000000,0.000000,0.000000,...,0.000000,131.000000,1.903500e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
75%,214.000000,2025.00000,9.25000,27963.500000,741.000000,115.250000,6446.000000,28.000000,2.000000,0.000000,...,0.000000,405.000000,4.405850e+04,12.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
max,285.000000,2025.00000,12.00000,569362.000000,21781.000000,2996.000000,88648.000000,588.000000,252.000000,96.000000,...,2.000000,6516.000000,1.165317e+06,5806.000000,164.000000,44.000000,152.000000,1.000000,0.0,90.000000

In [29]:
bizkaibus.loc[bizkaibus['TOTAL'].idxmax()]

_id                                                            83
EJERCICIO                                                    2024
MES                                                            10
CODIGO                                                      A3247
LINEA                                BILBAO-Aireportua/Aeropuerto
CREDITRANS                                               519383.0
CREDITRANS F20                                             8887.0
CREDITRANS F50                                              901.0
GIZATRANS                                                 49424.0
GIZATRANS 20                                                229.0
GIZATRANS 50                                                 14.0
BBCARD 24                                                    96.0
BBCARD 48                                                   158.0
BBCARD 72                                                   244.0
GAZTE 70                                                   4245.0
GAZTE 70 F20                                                262.0
GAZTE 70 F50                                                 88.0
GORO                                                       4883.0
GORO F20                                                    155.0
GORO F50                                                    318.0
B 50                                                       9985.0
B50 F20                                                     441.0
B50 F50                                                      34.0
B70                                                        2726.0
B70 F20                                                     146.0
B70 F50                                                      53.0
BORO                                                       9666.0
BORO F20                                                    112.0
BORO F50                                                     82.0
OCASIONAL                                                531070.0
FAMILIA NUMEROSA                                            260.0
MENORES DE 6 ANOS                                         12223.0
ACOMPANANTE INVIDENTE-PMRS                                  319.0
METRO                                                         0.0
PUP AVERIADO                                                  0.0
EMPRESA                                                      2747
TOTAL                                                   1165317.0
BAT                                                        5806.0
BAT F20                                                     164.0
BAT F50                                                      44.0
BAT BEREZI                                                  152.0
BAT BEREZI F20                                                0.0
BAT BEREZI F50                                                0.0
ACOMPANANTE GRATIS INVIDENTE-PMRS                             0.0
Name: 937, dtype: object